name: robot_sim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pytorch
  - setuptools<81
  - pip
  - pip:
      - mujoco
      - mujoco-warp
      - warp-lang
